// src/games/gameHelp.js
// Rules, objectives, AI info, and tips for all 10 games

export const GAME_HELP = {
    chess: {
        tagline: 'The classic game of strategy',
        objective: 'Checkmate your opponent\'s King — put it under attack with no escape.',
        rules: [
            'Each player controls 16 pieces: 1 King, 1 Queen, 2 Rooks, 2 Bishops, 2 Knights, 8 Pawns.',
            'Players alternate turns, moving one piece per turn.',
            'Capture enemy pieces by moving onto their square.',
            'Pawns move forward 1 square (2 on first move) and capture diagonally.',
            'The King can castle with a Rook if neither has moved and no pieces are between them.',
            'A King in "check" must be moved out of check immediately.',
            'Checkmate = King is in check with no legal move. Game over.',
        ],
        tip: 'Control the center early. Develop your Knights and Bishops before moving the Queen.',
        aiInfo: 'The AI uses Minimax search with Alpha-Beta pruning at depth 3. It evaluates piece values, board control, king safety, and mobility. Expect a strong mid-level challenge — not beatable by clicking randomly!',
    },
    checkers: {
        tagline: 'Jump and capture to dominate',
        objective: 'Capture all opponent pieces, or block them so they can\'t move.',
        rules: [
            'Pieces move diagonally on dark squares only.',
            'Regular pieces can only move forward.',
            'Capture by jumping over an opponent\'s piece into an empty square behind it.',
            'Multiple jumps in one turn are required if available.',
            'Reach the opponent\'s back row to become a King — Kings move in all 4 diagonal directions.',
            'If a capture is available, you must take it.',
        ],
        tip: 'Keep your back row intact as long as possible to prevent the opponent from Kinging.',
        aiInfo: 'The AI uses Minimax with Alpha-Beta pruning, prioritizing captures, kings, and board control. It looks 5 moves ahead — it won\'t miss forced jumps!',
    },
    tictactoe: {
        tagline: 'Three in a row wins',
        objective: 'Place three of your marks in a horizontal, vertical, or diagonal row.',
        rules: [
            'The board is a 3×3 grid.',
            'Players take turns: one plays X, the other O.',
            'Click any empty cell to place your mark.',
            'First to get 3 in a row (horizontal, vertical, or diagonal) wins.',
            'If all 9 cells are filled with no winner — it\'s a draw.',
        ],
        tip: 'Always take the center if it\'s free. The corners are the second-best positions.',
        aiInfo: 'The AI plays a mathematically perfect game using the full Minimax algorithm. It will never lose — at best you can draw. Try to force a draw!',
    },
    connectfour: {
        tagline: 'Drop discs, connect four to win',
        objective: 'Connect four of your discs in a row — horizontally, vertically, or diagonally.',
        rules: [
            'The board is 6 rows × 7 columns.',
            'Players alternate dropping one disc per turn into any column.',
            'Discs fall to the lowest empty row in the chosen column.',
            'First player to connect 4 discs in a row wins.',
            'If the board fills up with no winner — it\'s a draw.',
        ],
        tip: 'Build your strategy in the center columns. Diagonal threats are the hardest to defend against.',
        aiInfo: 'The AI uses Minimax with Alpha-Beta pruning at depth 6, with smart heuristics for center control, blocking threats, and building forks. It plays like a skilled human opponent.',
    },
    battleship: {
        tagline: 'Naval combat on a 10×10 grid',
        objective: 'Sink all 5 enemy ships before they sink yours.',
        rules: [
            'Each player has a 10×10 grid with 5 hidden ships (sizes 5, 4, 3, 3, 2).',
            'Ships are placed horizontally or vertically — they cannot overlap.',
            'Players take turns calling out grid coordinates to "fire" at.',
            'A hit = fire on a ship square. A miss = open water. Ships sink when all squares are hit.',
            'The player who sinks all opponent ships first wins.',
        ],
        tip: 'After a hit, focus fire on adjacent cells to sink the ship quickly.',
        aiInfo: 'The AI uses Hunt/Target strategy: it fires randomly until a hit, then hunts along axes to sink the ship. This mimics how expert players think.',
    },
    minesweeper: {
        tagline: 'Race to clear the minefield',
        objective: 'Reveal all non-mine cells on the board as fast as possible without hitting a mine.',
        rules: [
            'The board contains hidden mines.',
            'Click a cell to reveal it. Numbers show how many mines are in the 8 surrounding cells.',
            'Right-click (or long-press) to flag a suspected mine.',
            'Reveal all non-mine cells to win.',
            'Clicking a mine ends the game immediately.',
        ],
        tip: 'Start from the corners and edges. Use the numbers to deduce mine locations logically.',
        aiInfo: 'In solo mode, your time is tracked and displayed. The AI shows a ghost cursor demonstrating optimal moves after you complete. Compete against your own best time!',
    },
    uno: {
        tagline: 'A wild card game — last card wins',
        objective: 'Be the first player to play all your cards.',
        rules: [
            'Each player starts with 7 cards.',
            'Match the top card of the discard pile by color, number, or symbol.',
            'Special cards: Skip (skip next player), Reverse (reverse order), Draw 2 (next player draws 2), Wild (change color), Wild Draw 4 (next draws 4 + color change).',
            'If you can\'t play a card, draw one from the deck.',
            'Shout "One Card!" when you have 1 card left (here it\'s automatic).',
            'First to empty their hand wins!',
        ],
        tip: 'Save Wild Draw 4 for when you\'re desperate. Playing it too early wastes its power.',
        aiInfo: 'The AI uses a strategic rule system: it prioritizes playable cards, saves powerful cards, and targets opponents with the fewest cards. Expect smart card play!',
    },
    wordguess: {
        tagline: 'Guess the hidden word letter by letter',
        objective: 'Guess the secret word before you run out of attempts.',
        rules: [
            'A random English word is chosen. Its length is shown as empty blanks.',
            'Click letters on the keyboard to guess. Correct letters are revealed in place.',
            'Wrong letters are marked — you have 6 incorrect guesses before it\'s game over.',
            'Each body part of the hangman represents one wrong guess.',
            'Guess all letters in the word before the hangman is complete to win.',
        ],
        tip: 'Start with common letters: E, T, A, O, I, N, S. Avoid rare letters like Z, X, Q early on.',
        aiInfo: 'In VS AI mode, the AI uses English letter frequency analysis to guess letters in optimal order. You both solve the same word — who guesses it in fewer wrong attempts wins!',
    },
    rockpaperscissors: {
        tagline: 'Read your opponent in 5 rounds',
        objective: 'Win the best of 5 rounds by choosing a weapon that beats your opponent\'s.',
        rules: [
            '🪨 Rock beats [SCISSORS] Scissors',
            '[PAPER] Paper beats 🪨 Rock',
            '[SCISSORS] Scissors beats [PAPER] Paper',
            'Both players reveal simultaneously. Win = +1 point, Tie = no points.',
            'First to 3 wins claims victory in the best-of-5 series.',
        ],
        tip: 'Most players unconsciously repeat their choice after a loss. Switch it up!',
        aiInfo: 'The AI uses Markov chain pattern recognition — it tracks your last 5 moves and predicts what you\'ll do next. Playing randomly is actually the best counter-strategy!',
    },
    trivia: {
        tagline: 'Answer faster and smarter than the AI',
        objective: 'Score more points than the AI by answering trivia questions correctly and quickly.',
        rules: [
            'Each round has a question with 4 answer options.',
            'You have 15 seconds to answer each question.',
            'Correct answer = 10 points. Bonus points for answering faster.',
            'The AI answers after a realistic delay — it sometimes gets it wrong too.',
            'After 10 questions, highest score wins.',
        ],
        tip: 'When unsure, eliminate obviously wrong answers first. Two choices left = 50/50!',
        aiInfo: 'The AI has a configurable accuracy rating: it gets ~70% of questions right on purpose, with a realistic 1–5 second "thinking" delay to feel natural.',
    },
};
